# Generated by Django 3.0.6 on 2023-02-02 16:53

import app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default-title', max_length=255)),
                ('descr', models.CharField(blank=True, default='default-descr', max_length=255)),
                ('money', app.fields.AssetField()),
            ],
        ),
    ]
