# Generated by Django 3.0.6 on 2023-02-03 08:38

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=app.fields.AssetField(blank=True, null=True),
        ),
    ]
